# Operasi Baris Elementer (OBE)

Operasi Baris Elementer (OBE) adalah sekumpulan manipulasi aljabar yang dilakukan pada baris-baris suatu matriks. Dalam konteks Sistem Persamaan Linear (SPL), OBE digunakan untuk menyederhanakan matriks koefisien (biasanya dalam bentuk *Augmented Matrix*) tanpa mengubah himpunan penyelesaian dari sistem tersebut.

**Tujuan Utama:**
Mengubah matriks yang kompleks menjadi bentuk yang lebih sederhana (seperti bentuk eselon) sehingga solusi variabel dapat ditemukan dengan lebih mudah melalui substitusi balik atau pembacaan langsung.

## Tiga Jenis Operasi Dasar

Terdapat tiga jenis operasi standar yang diizinkan dalam OBE. Misalkan $R_i$ merepresentasikan baris ke-$i$:

1.  **Pertukaran Baris ($R_i \leftrightarrow R_j$):**
    Menukar posisi antara baris ke-$i$ dan baris ke-$j$. Operasi ini berguna jika kita membutuhkan angka bukan nol di posisi pivot.
2.  **Perkalian Baris dengan Konstanta Tak Nol ($k \cdot R_i \to R_i$):**
    Mengalikan setiap elemen dalam satu baris dengan bilangan riil $k$ (di mana $k \neq 0$). Contoh: mengubah angka pivot menjadi 1 agar perhitungan lebih sederhana.
3.  **Penjumlahan Kelipatan Baris ($R_i + kR_j \to R_i$):**
    Menambahkan kelipatan dari baris lain ke suatu baris. Ini adalah operasi paling krusial untuk menghasilkan angka nol di bawah atau di atas pivot.

Ketiga operasi ini merupakan fondasi dari metode **Eliminasi Gauss** dan **Eliminasi Gauss-Jordan**.

## Relevansi dan Kegunaan OBE

OBE bukan sekadar manipulasi angka, melainkan alat fundamental dalam Aljabar Linear untuk:
- **Menyelesaikan SPL:** Mengubah matriks menjadi bentuk segitiga untuk kemudahan eliminasi.
- **Mencari Invers Matriks:** Menggunakan metode eliminasi pada matriks berdampingan $[A | I]$.
- **Menghitung Determinan:** Beberapa operasi OBE mempermudah perhitungan determinan (dengan memperhatikan perubahan tanda saat tukar baris).
- **Menentukan Rank:** Mengetahui jumlah baris yang bebas linear dalam sebuah matriks.

## Sasaran Akhir: Bentuk Eselon

Melalui serangkaian OBE, kita bertujuan membawa matriks ke salah satu dari dua bentuk standar:

### a. Row Echelon Form (REF) / Bentuk Eselon Baris
Matriks dikatakan berada dalam bentuk eselon baris jika memenuhi:
1.  Semua baris yang seluruh elemennya nol berada di bagian paling bawah.
2.  **Leading entry** (elemen pertama yang bukan nol) dari setiap baris berada di sebelah kanan leading entry baris di atasnya.
3.  Di bawah setiap leading entry, semua elemennya adalah nol.

### b. Reduced Row Echelon Form (RREF) / Bentuk Eselon Baris Terreduksi
Bentuk yang lebih spesifik dan unik, dengan tambahan syarat:
1.  Setiap leading entry (pivot) harus bernilai **1**.
2.  Setiap kolom yang memiliki pivot bernilai 1, semua elemen lain di kolom tersebut (baik di atas maupun di bawah pivot) harus bernilai **0**.

## Konsep Pivot (*Leading Entry*)

**Pivot** adalah elemen pertama yang tidak bernilai nol dalam sebuah baris (dihitung dari kiri ke kanan).
- **Fungsi Utama:** Digunakan sebagai "jangkar" untuk mengeliminasi (membuat jadi nol) angka-angka yang berada di kolom yang sama pada baris-baris lainnya.
- Dalam bentuk RREF, pivot idealnya bernilai 1 untuk menyederhanakan interpretasi solusi.

## Prosedur Eliminasi Gauss

Secara sistematis, alur pengerjaannya adalah sebagai berikut:

1.  **Identifikasi Pivot:** Cari elemen bukan nol pertama pada kolom paling kiri yang tersedia. Jika perlu, gunakan operasi tukar baris.
2.  **Eliminasi Bawah:** Gunakan operasi penjumlahan kelipatan baris untuk mengubah semua angka di bawah pivot tersebut menjadi nol.
3.  **Iterasi:** Pindah ke baris dan kolom berikutnya, lalu ulangi langkah 1 dan 2 hingga matriks mencapai bentuk **REF**.
4.  **Opsional (Gauss-Jordan):** Lanjutkan proses untuk menolkan angka di *atas* pivot dan mengubah pivot menjadi 1 untuk mencapai bentuk **RREF**.

**Penyelesaian Akhir:**
Setelah mencapai bentuk REF, kita menggunakan **Substitusi Balik (Back-Substitution)** mulai dari baris terbawah untuk menemukan nilai setiap variabel. Jika menggunakan RREF, solusi seringkali dapat langsung dibaca dari matriks tersebut.

In [22]:
import numpy as np

# Inisialisasi Matriks A
A = np.array([
    [0, 2, 4],
    [1, 3, 5],
    [2, 4, 8]
], dtype=float)

print("Matriks Awal:")
print(A)

# 1. Pertukaran Baris (R1 <-> R2)
# Menukar baris 0 dengan baris 1 karena A[0,0] adalah 0 (tidak bisa jadi pivot)
A[[0, 1]] = A[[1, 0]]

print("\nSetelah Pertukaran Baris (R1 <-> R2):")
print(A)

Matriks Awal:
[[0. 2. 4.]
 [1. 3. 5.]
 [2. 4. 8.]]

Setelah Pertukaran Baris (R1 <-> R2):
[[1. 3. 5.]
 [0. 2. 4.]
 [2. 4. 8.]]


In [23]:
# Melanjutkan dari matriks sebelumnya
# 2. Perkalian Baris dengan Konstanta (1/2 * R2 -> R2)
# Misal kita ingin menyederhanakan baris ke-3 (indeks 2)
A[2] = 0.5 * A[2]

print("Setelah Perkalian Baris (0.5 * R3 -> R3):")
print(A)

Setelah Perkalian Baris (0.5 * R3 -> R3):
[[1. 3. 5.]
 [0. 2. 4.]
 [1. 2. 4.]]


In [24]:
# Melanjutkan dari matriks sebelumnya
# 3. Penjumlahan Kelipatan Baris (R3 + (-1)*R1 -> R3)
# Menggunakan baris 1 (indeks 0) untuk menolkan elemen di baris 3 (indeks 2) kolom 1
# Rumus: R3 = R3 - 1*R1
A[2] = A[2] - 1 * A[0]

print("Setelah Penjumlahan Kelipatan Baris (R3 - R1 -> R3):")
print(A)

Setelah Penjumlahan Kelipatan Baris (R3 - R1 -> R3):
[[ 1.  3.  5.]
 [ 0.  2.  4.]
 [ 0. -1. -1.]]


In [25]:
# Melanjutkan ke Row Echelon Form (REF)
# Pada langkah sebelumnya (sebelum sel ini), matriks A adalah:
# [[ 1.  3.  5.]
#  [ 0.  2.  4.]
#  [ 0. -1. -1.]]

# Langkah 4: Hilangkan angka -1 di baris 3 kolom 2 menggunakan baris 2 (R2)
# Kita bisa menjumlahkan R3 dengan 0.5 * R2 agar elemen di kolom 2 menjadi 0
# R3 = R3 + 0.5 * R2
A[2] = A[2] + 0.5 * A[1]

print("Setelah R3 + 0.5 * R2 (Mencapai Bentuk REF):")
print(A)

# Langkah 5 (Opsional): Membuat pivot menjadi 1 (Leading 1)
# Baris 2 memiliki pivot 2. Kita bagi dengan 2.
# R2 = 1/2 * R2
A[1] = 0.5 * A[1]

print("\nSetelah R2 * 0.5 (Leading 1 pada baris 2):")
print(A)

Setelah R3 + 0.5 * R2 (Mencapai Bentuk REF):
[[1. 3. 5.]
 [0. 2. 4.]
 [0. 0. 1.]]

Setelah R2 * 0.5 (Leading 1 pada baris 2):
[[1. 3. 5.]
 [0. 1. 2.]
 [0. 0. 1.]]


<iframe scrolling="no" title="Graph the Line" src="https://www.geogebra.org/material/iframe/id/qzgpq9gz/width/631/height/400/border/888888/sfsb/true/smb/false/stb/false/stbh/false/ai/false/asb/false/sri/true/rc/false/ld/false/sdz/true/ctl/false" width="631px" height="400px" style="border:0px;"> </iframe>


<iframe scrolling="no" title="Graph the Line" src="https://www.geogebra.org/material/iframe/id/kpqftj8p/width/631/height/400/border/888888/sfsb/true/smb/false/stb/false/stbh/false/ai/false/asb/false/sri/true/rc/false/ld/false/sdz/true/ctl/false" width="631px" height="400px" style="border:0px;"> </iframe>

<iframe scrolling="no" title="Graph the Line" src="https://www.geogebra.org/material/iframe/id/mx8ejtvv/width/631/height/400/border/888888/sfsb/true/smb/false/stb/false/stbh/false/ai/false/asb/false/sri/true/rc/false/ld/false/sdz/true/ctl/false" width="631px" height="400px" style="border:0px;"> </iframe>