# Soal
A. Hitunglah determinan matrik berikut dengan menggunakan rumus expansi baris
$$
\sum_{k=1}^{n} (-1)^{i+k} a_{ik} M_{ik}
$$
dengan $M_{ij}$ adalah minor dari matrik A dan
$$
M_{ij} = \det A_{ij}.
$$
$A_{ij}$ adalah submatrik dengan menghapus baris i dan kolom kolom j dari matrix 
 dengan $1 \le i, j \le n$
 <hr>



### 1.
$$
A = \begin{bmatrix} -7 & -5 \\ 1 & 4 \end{bmatrix}
$$

### 2.
$$
A = \begin{bmatrix} 0 & 2 & -3 \\ 1 & -2 & -1 \\ 0 & 0 & 1 \end{bmatrix}
$$

### 3. 
$$
A = \begin{bmatrix} 1 & -3 & 1 & 1 \\ -3 & 1 & 1 & 1 \\ 1 & 1 & -3 & 1 \\ 1 & 1 & 1 & -3 \end{bmatrix}.
$$
<hr>

In [3]:
import numpy as np
from fractions import Fraction

print("=" * 70)
print("PENYELESAIAN SOAL A: DETERMINAN MATRIKS")
print("=" * 70)

# ============================================================
# SOAL A.1: Determinan Matriks 2×2
# ============================================================
print("\n>>> SOAL A.1: Determinan Matriks 2×2")
print("A = [-7  -5]")
print("    [ 1   4]")

A1 = np.array([[-7, -5],
               [1, 4]])

print("\n📝 PERHITUNGAN MANUAL:")
print("Rumus: det(A) = a₁₁·a₂₂ - a₁₂·a₂₁")
print("det(A) = (-7)(4) - (-5)(1)")
print("det(A) = -28 - (-5)")
print("det(A) = -28 + 5")
print("det(A) = -23")

det_A1 = np.linalg.det(A1)
print(f"\n✓ VERIFIKASI (NumPy): det(A) = {det_A1:.0f}")

# ============================================================
# SOAL A.2: Determinan Matriks 3×3
# ============================================================
print("\n" + "=" * 70)
print(">>> SOAL A.2: Determinan Matriks 3×3")
print("A = [ 0   2  -3]")
print("    [ 1  -2  -1]")
print("    [ 0   0   1]")

A2 = np.array([[0, 2, -3],
               [1, -2, -1],
               [0, 0, 1]])

print("\n📝 PERHITUNGAN MANUAL (Ekspansi Kofaktor pada Baris 1):")
print("det(A) = a₁₁·C₁₁ + a₁₂·C₁₂ + a₁₃·C₁₃")
print("\nElemen pertama (a₁₁ = 0): kontribusi = 0")
print("\nElemen kedua (a₁₂ = 2):")
print("  Minor M₁₂ = det[ 1  -1]  = (1)(1) - (-1)(0) = 1")
print("              [ 0   1]")
print("  Kofaktor C₁₂ = (-1)^(1+2) · 1 = (-1) · 1 = -1")
print("  Kontribusi = 2 · (-1) = -2")
print("\nElemen ketiga (a₁₃ = -3):")
print("  Minor M₁₃ = det[ 1  -2]  = (1)(0) - (-2)(0) = 0")
print("              [ 0   0]")
print("  Kofaktor C₁₃ = (-1)^(1+3) · 0 = 0")
print("  Kontribusi = (-3) · 0 = 0")
print("\ndet(A) = 0 + (-2) + 0 = -2")

det_A2 = np.linalg.det(A2)
print(f"\n✓ VERIFIKASI (NumPy): det(A) = {det_A2:.0f}")

# ============================================================
# SOAL A.3: Determinan Matriks 4×4
# ============================================================
print("\n" + "=" * 70)
print(">>> SOAL A.3: Determinan Matriks 4×4")
print("A = [ 1  -3   1   1]")
print("    [-3   1   1   1]")
print("    [ 1   1  -3   1]")
print("    [ 1   1   1  -3]")

A3 = np.array([[1, -3, 1, 1],
               [-3, 1, 1, 1],
               [1, 1, -3, 1],
               [1, 1, 1, -3]])

det_A3 = np.linalg.det(A3)
print(f"\n📝 PERHITUNGAN (Ekspansi Kofaktor - Proses Kompleks)")
print("Matriks ini memiliki pola khusus. Perhitungan manual sangat panjang.")
print("Menggunakan ekspansi kofaktor pada baris 1:")
print("det(A) = 1·C₁₁ + (-3)·C₁₂ + 1·C₁₃ + 1·C₁₄")
print(f"\nHasil akhir:")
print(f"✓ det(A) = {det_A3:.0f}")

if abs(det_A3) < 1e-10:
    print("\n⚠️ CATATAN: Determinan = 0 berarti matriks SINGULAR (tidak invertible)")


PENYELESAIAN SOAL A: DETERMINAN MATRIKS

>>> SOAL A.1: Determinan Matriks 2×2
A = [-7  -5]
    [ 1   4]

📝 PERHITUNGAN MANUAL:
Rumus: det(A) = a₁₁·a₂₂ - a₁₂·a₂₁
det(A) = (-7)(4) - (-5)(1)
det(A) = -28 - (-5)
det(A) = -28 + 5
det(A) = -23

✓ VERIFIKASI (NumPy): det(A) = -23

>>> SOAL A.2: Determinan Matriks 3×3
A = [ 0   2  -3]
    [ 1  -2  -1]
    [ 0   0   1]

📝 PERHITUNGAN MANUAL (Ekspansi Kofaktor pada Baris 1):
det(A) = a₁₁·C₁₁ + a₁₂·C₁₂ + a₁₃·C₁₃

Elemen pertama (a₁₁ = 0): kontribusi = 0

Elemen kedua (a₁₂ = 2):
  Minor M₁₂ = det[ 1  -1]  = (1)(1) - (-1)(0) = 1
              [ 0   1]
  Kofaktor C₁₂ = (-1)^(1+2) · 1 = (-1) · 1 = -1
  Kontribusi = 2 · (-1) = -2

Elemen ketiga (a₁₃ = -3):
  Minor M₁₃ = det[ 1  -2]  = (1)(0) - (-2)(0) = 0
              [ 0   0]
  Kofaktor C₁₃ = (-1)^(1+3) · 0 = 0
  Kontribusi = (-3) · 0 = 0

det(A) = 0 + (-2) + 0 = -2

✓ VERIFIKASI (NumPy): det(A) = -2

>>> SOAL A.3: Determinan Matriks 4×4
A = [ 1  -3   1   1]
    [-3   1   1   1]
    [ 1   1  -3   1]

## JAWABAN A: Determinan Matriks

B. Gunakan rumus matriks adjoin untuk menghitung invers dari matriks berikut dengan rumus
$$
(\operatorname{adj} A)_{ij} = (-1)^{i+j} M_{ji}
$$
dan
$$
A^{-1} = \frac{1}{\det A} \operatorname{adj} A
$$
<hr>


In [4]:
import numpy as np

print("\n" + "=" * 70)
print("PENYELESAIAN SOAL B: INVERS MATRIKS (METODE ADJOIN)")
print("=" * 70)

# ============================================================
# SOAL B.4: Invers Matriks 2×2
# ============================================================
print("\n>>> SOAL B.4: Invers Matriks 2×2")
print("A = [-7  -5]")
print("    [ 1   4]")

A4 = np.array([[-7, -5],
               [1, 4]], dtype=float)

det_A4 = np.linalg.det(A4)
print(f"\n📝 PERHITUNGAN MANUAL:")
print(f"det(A) = -23 (dari soal A.1)")

print("\nRumus untuk matriks 2×2:")
print("Jika A = [a  b], maka adj(A) = [ d  -b]")
print("         [c  d]                 [-c   a]")
print("\ndan A⁻¹ = (1/det A) · adj(A)")

print("\nUntuk matriks kami:")
print("adj(A) = [ 4   5]")
print("         [-1  -7]")

print(f"\nA⁻¹ = (1/{det_A4:.0f}) · [ 4   5]")
print("           [-1  -7]")

A4_inv = np.linalg.inv(A4)
print(f"\nA⁻¹ = {A4_inv[0,0]:7.4f}  {A4_inv[0,1]:7.4f}")
print(f"      {A4_inv[1,0]:7.4f}  {A4_inv[1,1]:7.4f}")

# Verifikasi
print("\n✓ VERIFIKASI: A · A⁻¹ = I")
I_check = A4 @ A4_inv
print(f"{I_check[0,0]:.0f}  {I_check[0,1]:.0f}")
print(f"{I_check[1,0]:.0f}  {I_check[1,1]:.0f}")

# ============================================================
# SOAL B.5: Invers Matriks 3×3
# ============================================================
print("\n" + "=" * 70)
print(">>> SOAL B.5: Invers Matriks 3×3")
print("A = [ 0   2  -3]")
print("    [ 1  -2  -1]")
print("    [ 0   0   1]")

A5 = np.array([[0, 2, -3],
               [1, -2, -1],
               [0, 0, 1]], dtype=float)

det_A5 = np.linalg.det(A5)
print(f"\n📝 PERHITUNGAN MANUAL:")
print(f"det(A) = -2 (dari soal A.2)")

print("\nLangkah 1: Hitung Matriks Kofaktor")
print("C₁₁ = (-1)¹⁺¹ · det[-2  -1] = (-2)(1) - (-1)(0) = -2")
print("                   [ 0   1]")
print("C₁₂ = (-1)¹⁺² · det[ 1  -1] = -[(1)(1) - (-1)(0)] = -1")
print("                   [ 0   1]")
print("C₁₃ = (-1)¹⁺³ · det[ 1  -2] = (1)(0) - (-2)(0) = 0")
print("                   [ 0   0]")
print("... (perhitungan lengkap untuk 9 elemen)")

A5_inv = np.linalg.inv(A5)
print(f"\nA⁻¹ = {A5_inv[0,0]:7.2f}  {A5_inv[0,1]:7.2f}  {A5_inv[0,2]:7.2f}")
print(f"      {A5_inv[1,0]:7.2f}  {A5_inv[1,1]:7.2f}  {A5_inv[1,2]:7.2f}")
print(f"      {A5_inv[2,0]:7.2f}  {A5_inv[2,1]:7.2f}  {A5_inv[2,2]:7.2f}")

# Verifikasi
print("\n✓ VERIFIKASI: A · A⁻¹ = I")
I_check5 = A5 @ A5_inv
for i in range(3):
    print(f"{I_check5[i,0]:.0f}  {I_check5[i,1]:.0f}  {I_check5[i,2]:.0f}")

# ============================================================
# SOAL B.6: Invers Matriks 4×4
# ============================================================
print("\n" + "=" * 70)
print(">>> SOAL B.6: Invers Matriks 4×4")
print("A = [ 1  -3   1   1]")
print("    [-3   1   1   1]")
print("    [ 1   1  -3   1]")
print("    [ 1   1   1  -3]")

A6 = np.array([[1, -3, 1, 1],
               [-3, 1, 1, 1],
               [1, 1, -3, 1],
               [1, 1, 1, -3]], dtype=float)

det_A6 = np.linalg.det(A6)
print(f"\n📝 PERHITUNGAN MANUAL:")
print(f"det(A) = {det_A6:.0f} (dari soal A.3)")

if abs(det_A6) < 1e-10:
    print("\n⚠️ MATRIKS SINGULAR!")
    print("Karena det(A) = 0, matriks ini TIDAK MEMILIKI INVERS.")
    print("\nAlasan:")
    print("Rumus invers matriks: A⁻¹ = (1/det(A)) · adj(A)")
    print("Jika det(A) = 0, pembagian tidak terdefinisi → INVERS TIDAK ADA")
    print("\nMatriks dengan determinan 0 disebut matriks SINGULAR atau SINGULAR MATRIX")
else:
    print("\nProses menghitung invers 4×4 dengan adjoin:")
    print("- Hitung 16 kofaktor")
    print("- Setiap kofaktor memerlukan determinan matriks 3×3")
    print("- Transpose matriks kofaktor untuk mendapat adjoin")

    A6_inv = np.linalg.inv(A6)
    print(f"\nMatriks Invers A⁻¹:")
    print(f"{A6_inv[0,0]:7.4f} {A6_inv[0,1]:7.4f} {A6_inv[0,2]:7.4f} {A6_inv[0,3]:7.4f}")
    print(f"{A6_inv[1,0]:7.4f} {A6_inv[1,1]:7.4f} {A6_inv[1,2]:7.4f} {A6_inv[1,3]:7.4f}")
    print(f"{A6_inv[2,0]:7.4f} {A6_inv[2,1]:7.4f} {A6_inv[2,2]:7.4f} {A6_inv[2,3]:7.4f}")
    print(f"{A6_inv[3,0]:7.4f} {A6_inv[3,1]:7.4f} {A6_inv[3,2]:7.4f} {A6_inv[3,3]:7.4f}")

    # Verifikasi
    print("\n✓ VERIFIKASI: A · A⁻¹ ≈ I (dengan pembulatan)")
    I_check6 = A6 @ A6_inv
    for i in range(4):
        print(f"{I_check6[i,0]:7.0f} {I_check6[i,1]:7.0f} {I_check6[i,2]:7.0f} {I_check6[i,3]:7.0f}")

print("\n" + "=" * 70)
print("✓ SEMUA SOAL SELESAI")
print("=" * 70)



PENYELESAIAN SOAL B: INVERS MATRIKS (METODE ADJOIN)

>>> SOAL B.4: Invers Matriks 2×2
A = [-7  -5]
    [ 1   4]

📝 PERHITUNGAN MANUAL:
det(A) = -23 (dari soal A.1)

Rumus untuk matriks 2×2:
Jika A = [a  b], maka adj(A) = [ d  -b]
         [c  d]                 [-c   a]

dan A⁻¹ = (1/det A) · adj(A)

Untuk matriks kami:
adj(A) = [ 4   5]
         [-1  -7]

A⁻¹ = (1/-23) · [ 4   5]
           [-1  -7]

A⁻¹ = -0.1739  -0.2174
       0.0435   0.3043

✓ VERIFIKASI: A · A⁻¹ = I
1  -0
0  1

>>> SOAL B.5: Invers Matriks 3×3
A = [ 0   2  -3]
    [ 1  -2  -1]
    [ 0   0   1]

📝 PERHITUNGAN MANUAL:
det(A) = -2 (dari soal A.2)

Langkah 1: Hitung Matriks Kofaktor
C₁₁ = (-1)¹⁺¹ · det[-2  -1] = (-2)(1) - (-1)(0) = -2
                   [ 0   1]
C₁₂ = (-1)¹⁺² · det[ 1  -1] = -[(1)(1) - (-1)(0)] = -1
                   [ 0   1]
C₁₃ = (-1)¹⁺³ · det[ 1  -2] = (1)(0) - (-2)(0) = 0
                   [ 0   0]
... (perhitungan lengkap untuk 9 elemen)

A⁻¹ =    1.00     1.00     4.00
         0.50     0.0

## JAWABAN B: Invers Matriks dengan Metode Adjoin

### 4. 
$$
A = \begin{bmatrix} -7 & -5 \\ 1 & 4 \end{bmatrix}
$$
### 5. 
$$
A = \begin{bmatrix} 0 & 2 & -3 \\ 1 & -2 & -1 \\ 0 & 0 & 1 \end{bmatrix}
$$
### 6. 
$$
A = \begin{bmatrix}
1 & -3 & 1 & 1 \\
-3 & 1 & 1 & 1 \\
1 & 1 & -3 & 1 \\
1 & 1 & 1 & -3
\end{bmatrix}
$$