# Tugas 
membuat contoh penyelesaian sistem persamaan linier tiga variabel dan empat variabel dengan menggunakan eliminasi gaussian, cara mencarinya atau prosesnya bisa menggunakan tools bapak tadi nanti baru ke jupyter notebook

## SPL 3 VARIABEL (ELIMINASI GAUSIAN)

### Contoh SPL 3 Variabel
Kita akan menyelesaikan sistem persamaan berikut:
$$
\begin{cases}
1x + 1y + 1z = 6 \\
2x + 3y + 1z = 10 \\
1x + 2y + 3z = 13
\end{cases}
$$

**Langkah-langkah Eliminasi Gauss (Proses Detail):**

1.  **Representasi Matriks Augmented:**
    $$
    \begin{bmatrix}
    1 & 1 & 1 & | & 6 \\
    2 & 3 & 1 & | & 10 \\
    1 & 2 & 3 & | & 13
    \end{bmatrix}
    $$

2.  **Langkah 1: Normalisasi Baris 1**
    *   Karena $A_{11}$ sudah 1, tidak ada perubahan: $R_1 \to R_1$

3.  **Langkah 2: Eliminasi Elemen di Bawah Pivot Kolom 1**
    *   **Baris 2:** $R_2 = R_2 - 2R_1 \implies [2, 3, 1, 10] - 2[1, 1, 1, 6] = [0, 1, -1, -2]$
    *   **Baris 3:** $R_3 = R_3 - 1R_1 \implies [1, 2, 3, 13] - 1[1, 1, 1, 6] = [0, 1, 2, 7]$

4.  **Langkah 3: Normalisasi Baris 2**
    *   Karena $A_{22}$ sudah 1, tidak ada perubahan: $R_2 \to R_2$

5.  **Langkah 4: Eliminasi Elemen di Bawah Pivot Kolom 2**
    *   **Baris 3:** $R_3 = R_3 - 1R_2 \implies [0, 1, 2, 7] - 1[0, 1, -1, -2] = [0, 0, 3, 9]$

6.  **Langkah 5: Normalisasi Baris 3**
    *   $R_3 = \frac{1}{3}R_3 \implies \frac{1}{3}[0, 0, 3, 9] = [0, 0, 1, 3]$

7.  **Hasil Akhir (Bentuk REF):**
    $$
    \begin{bmatrix}
    1 & 1 & 1 & | & 6 \\
    0 & 1 & -1 & | & -2 \\
    0 & 0 & 1 & | & 3
    \end{bmatrix}
    $$
    Setelah ini kita lakukan *Back Substitution* untuk mendapatkan nilai $x, y, z$.

In [ ]:
import numpy as np

# 1. Definisikan Matriks Augmented
A = np.array([
    [1, 1, 1, 6],
    [2, 3, 1, 10],
    [1, 2, 3, 13]
], dtype=float)

print("Matriks Awal (Augmented Matrix):")
print(A)
print("-" * 30)

# 2. Proses Eliminasi Gaussian dengan Cetak Langkah per Langkah
n = len(A)

for i in range(n):
    # Membuat pivot baris i kolom i menjadi 1 (Normalisasi)
    pivot = A[i][i]
    if pivot != 0:
        A[i] = A[i] / pivot
        if pivot != 1:
            print(f"Langkah {i+1}.1: Normalisasi Baris {i+1} (R{i+1} / {pivot:.2f})")
            print(A)
    
    # Menolkan elemen di bawah pivot
    for j in range(i + 1, n):
        factor = A[j][i]
        if factor != 0:
            A[j] = A[j] - factor * A[i]
            print(f"Langkah {i+1}.{j-i+1}: Eliminasi Baris {j+1} (R{j+1} - {factor:.2f} * R{i+1})")
            print(A)
    print("-" * 30)

print("\nMatriks setelah Eliminasi (Bentuk REF):")
print(A)

# 3. Substitusi Balik (Back Substitution)
x = np.zeros(n)
for i in range(n - 1, -1, -1):
    x[i] = A[i][-1] - np.sum(A[i][i+1:n] * x[i+1:n])

print("\nSolusi Sistem:")
print(f"x = {x[0]:.2f}")
print(f"y = {x[1]:.2f}")
print(f"z = {x[2]:.2f}")

Matriks Awal (Augmented Matrix):
[[ 1.  1.  1.  6.]
 [ 2.  3.  1. 10.]
 [ 1.  2.  3. 13.]]
------------------------------
Langkah 1.2: Eliminasi Baris 2 (R2 - 2.00 * R1)
[[ 1.  1.  1.  6.]
 [ 0.  1. -1. -2.]
 [ 1.  2.  3. 13.]]
Langkah 1.3: Eliminasi Baris 3 (R3 - 1.00 * R1)
[[ 1.  1.  1.  6.]
 [ 0.  1. -1. -2.]
 [ 0.  1.  2.  7.]]
------------------------------
Langkah 2.2: Eliminasi Baris 3 (R3 - 1.00 * R2)
[[ 1.  1.  1.  6.]
 [ 0.  1. -1. -2.]
 [ 0.  0.  3.  9.]]
------------------------------
Langkah 3.1: Normalisasi Baris 3 (R3 / 3.00)
[[ 1.  1.  1.  6.]
 [ 0.  1. -1. -2.]
 [ 0.  0.  1.  3.]]
------------------------------

Matriks setelah Eliminasi (Bentuk REF):
[[ 1.  1.  1.  6.]
 [ 0.  1. -1. -2.]
 [ 0.  0.  1.  3.]]

Solusi Sistem:
x = 2.00
y = 1.00
z = 3.00


## SPL 4 VARIABEL (ELIMINASI GAUSIAN)

### Sistem Persamaan Linear 4 Variabel (SPL 4V)

Kita akan menggunakan sistem yang memiliki solusi unik agar baris terakhir tidak menjadi nol:

$$
\begin{cases}
2x_1 + 3x_2 - x_3 + 4x_4 = 1 \\
1x_1 - 2x_2 + 2x_3 - 3x_4 = 2 \\
3x_1 + 1x_2 + 1x_3 + 2x_4 = 3 \\
-1x_1 + 4x_2 + 1x_3 - 2x_4 = 4
\end{cases}
$$

**Proses Detail Operasi Baris Elementer:**

#### 1. Matriks Augmented Awal
$$
\begin{bmatrix}
2 & 3 & -1 & 4 & | & 1 \\
1 & -2 & 2 & -3 & | & 2 \\
3 & 1 & 1 & 2 & | & 3 \\
-1 & 4 & 1 & -2 & | & 4
\end{bmatrix}
$$

#### 2. Kolom 1 (Pivot R1)
*   **Normalisasi R1:** $R_1 = \frac{R_1}{2} \implies [1, 1.5, -0.5, 2, 0.5]$
*   **Eliminasi R2:** $R_2 = R_2 - 1R_1 \implies [0, -3.5, 2.5, -5, 1.5]$
*   **Eliminasi R3:** $R_3 = R_3 - 3R_1 \implies [0, -3.5, 2.5, -4, 1.5]$
*   **Eliminasi R4:** $R_4 = R_4 - (-1)R_1 \implies [0, 5.5, 0.5, 0, 4.5]$

#### 3. Kolom 2 (Pivot R2)
*   **Normalisasi R2:** $R_2 = \frac{R_2}{-3.5} \implies [0, 1, -0.71, 1.43, -0.43]$
*   **Eliminasi R3:** $R_3 = R_3 - (-3.5)R_2 \implies [0, 0, 0, 1, 0]$
*   **Eliminasi R4:** $R_4 = R_4 - 5.5R_2 \implies [0, 0, 4.43, -7.86, 6.86]$

#### 4. Kolom 3 (Pivot R3)
*   **Tukar Baris:** Karena $A_{33}$ adalah 0, kita tukar $R_3$ dengan $R_4$:
    *   $R_3 \leftrightarrow R_4$
*   **Normalisasi R3:** $R_3 = \frac{R_3}{4.43} \implies [0, 0, 1, -1.77, 1.55]$
*   **Eliminasi R4:** $R_4$ sudah memiliki 0 di kolom 3 (tidak ada perubahan).

#### 5. Kolom 4 (Pivot R4)
*   **Normalisasi R4:** $R_4 = \frac{R_4}{1} \implies [0, 0, 0, 1, 0]$

Setelah langkah-langkah di atas, matriks akan berbentuk **Row Echelon Form (REF)** dengan angka 1 di setiap diagonal utamanya. Kemudian, proses dilanjutkan dengan **Eliminasi Mundur** untuk menolkan elemen di atas pivot hingga menjadi **Reduced Row Echelon Form (RREF)**.

In [ ]:
import numpy as np

# Matriks Augmented untuk SPL 4 Variabel
A_original = np.array([
    [2, 3, -1, 4, 1],
    [1, -2, 2, -3, 2],
    [3, 1, 1, 2, 3],
    [-1, 4, 1, -2, 4]
], dtype=float)

def solve_gauss_to_ref(A):
    n = len(A)
    print("=== PROSES ELIMINASI GAUSSIAN (MENUJU REF) ===")
    print("Matriks Awal:")
    print(A)
    print("-" * 30)

    for i in range(n):
        # 1. Cek Pivot dan Tukar Baris jika perlu
        if abs(A[i, i]) < 1e-10:
            for k in range(i + 1, n):
                if abs(A[k, i]) > 1e-10:
                    A[[i, k]] = A[[k, i]]
                    print(f"Langkah {i+1}.0: Tukar Baris {i+1} dengan Baris {k+1}")
                    print(A)
                    break
        
        # 2. Normalisasi Baris (Membuat Utama 1)
        pivot = A[i, i]
        if abs(pivot) > 1e-10:
            A[i] = A[i] / pivot
            print(f"Langkah {i+1}.1: Normalisasi Baris {i+1} (R{i+1} / {pivot:.2f})")
            print(A)
        
        # 3. Eliminasi elemen di bawah pivot
        for j in range(i + 1, n):
            factor = A[j, i]
            if abs(factor) > 1e-10:
                A[j] = A[j] - factor * A[i]
                print(f"Langkah {i+1}.{j-i+1}: Eliminasi R{j+1} (R{j+1} - ({factor:.2f}) * R{i+1})")
                print(A)
        print("-" * 30)
    
    return A

def solve_ref_to_rref(A):
    n = len(A)
    print("\n=== PROSES ELIMINASI GAUSS-JORDAN (MENUJU RREF) ===")
    
    # Eliminasi elemen di ATAS pivot
    for i in range(n - 1, -1, -1):
        for j in range(i - 1, -1, -1):
            factor = A[j, i]
            if abs(factor) > 1e-10:
                A[j] = A[j] - factor * A[i]
                print(f"Langkah Mundur: Eliminasi R{j+1} (R{j+1} - ({factor:.2f}) * R{i+1})")
                print(A)
    print("-" * 30)
    return A

# Jalankan proses
matrix_working = A_original.copy()
matrix_ref = solve_gauss_to_ref(matrix_working)

print("\nHASIL AKHIR BENTUK REF (Row Echelon Form):")
print(matrix_ref)

matrix_rref = solve_ref_to_rref(matrix_ref.copy())

print("\nHASIL AKHIR BENTUK RREF (Reduced Row Echelon Form):")
print(matrix_rref)

# Solusi Akhir dari RREF (Kolom Terakhir)
solusi = matrix_rref[:, -1]
print("\nSolusi Akhir:")
variables = ['x1', 'x2', 'x3', 'x4']
for var, val in zip(variables, solusi):
    print(f"{var} = {val:.4f}")

=== PROSES ELIMINASI GAUSSIAN (MENUJU REF) ===
Matriks Awal:
[[ 2.  3. -1.  4.  1.]
 [ 1. -2.  2. -3.  2.]
 [ 3.  1.  1.  2.  3.]
 [-1.  4.  1. -2.  4.]]
------------------------------
Langkah 1.1: Normalisasi Baris 1 (R1 / 2.00)
[[ 1.   1.5 -0.5  2.   0.5]
 [ 1.  -2.   2.  -3.   2. ]
 [ 3.   1.   1.   2.   3. ]
 [-1.   4.   1.  -2.   4. ]]
Langkah 1.2: Eliminasi R2 (R2 - (1.00) * R1)
[[ 1.   1.5 -0.5  2.   0.5]
 [ 0.  -3.5  2.5 -5.   1.5]
 [ 3.   1.   1.   2.   3. ]
 [-1.   4.   1.  -2.   4. ]]
Langkah 1.3: Eliminasi R3 (R3 - (3.00) * R1)
[[ 1.   1.5 -0.5  2.   0.5]
 [ 0.  -3.5  2.5 -5.   1.5]
 [ 0.  -3.5  2.5 -4.   1.5]
 [-1.   4.   1.  -2.   4. ]]
Langkah 1.4: Eliminasi R4 (R4 - (-1.00) * R1)
[[ 1.   1.5 -0.5  2.   0.5]
 [ 0.  -3.5  2.5 -5.   1.5]
 [ 0.  -3.5  2.5 -4.   1.5]
 [ 0.   5.5  0.5  0.   4.5]]
------------------------------
Langkah 2.1: Normalisasi Baris 2 (R2 / -3.50)
[[ 1.          1.5        -0.5         2.          0.5       ]
 [-0.          1.         -0.71428571  1.4

# Soal
A. Hitunglah determinan matrik berikut dengan menggunakan rumus expansi baris
$$
\sum_{k=1}^{n} (-1)^{i+k} a_{ik} M_{ik}
$$
dengan $M_{ij}$ adalah minior dari matrik A dan
$$
M_{ij} = \det A_{ij}.
$$
$A_{ij}$ adalah submatrik dengan menghapus baris i dan kolom kolom j dari matrix 
 dengan $1 \le i, j \le n$
 <hr>

