## TUGAS
Buat matrix transformasi 
A ke B
B ke C
D ke E
E ke F
<hr>

In [1]:
import numpy as np

# =====================================================
# 1. TRANSFORMASI A → B
# =====================================================

# Koordinat titik
A = (2, 3)
B = (2, 1)

print("TRANSFORMASI A → B")
print("Titik A =", A)
print("Titik B =", B)

# Menghitung perubahan koordinat
dx1 = B[0] - A[0]
dy1 = B[1] - A[1]

print("\nPerhitungan:")
print("Δx =", B[0], "-", A[0], "=", dx1)
print("Δy =", B[1], "-", A[1], "=", dy1)

# Membuat matriks translasi
TAB = np.array([
    [1, 0, dx1],
    [0, 1, dy1],
    [0, 0, 1]
])

print("\nMatriks Transformasi A → B:")
print(TAB)

print("\n=====================================\n")


# =====================================================
# 2. TRANSFORMASI B → C
# =====================================================

B = (2, 1)
C = (4, 1)

print("TRANSFORMASI B → C")
print("Titik B =", B)
print("Titik C =", C)

dx2 = C[0] - B[0]
dy2 = C[1] - B[1]

print("\nPerhitungan:")
print("Δx =", C[0], "-", B[0], "=", dx2)
print("Δy =", C[1], "-", B[1], "=", dy2)

TBC = np.array([
    [1, 0, dx2],
    [0, 1, dy2],
    [0, 0, 1]
])

print("\nMatriks Transformasi B → C:")
print(TBC)

print("\n=====================================\n")


# =====================================================
# 3. TRANSFORMASI D → E
# =====================================================

D = (2, 4)
E = (2, 0)

print("TRANSFORMASI D → E")
print("Titik D =", D)
print("Titik E =", E)

dx3 = E[0] - D[0]
dy3 = E[1] - D[1]

print("\nPerhitungan:")
print("Δx =", E[0], "-", D[0], "=", dx3)
print("Δy =", E[1], "-", D[1], "=", dy3)

TDE = np.array([
    [1, 0, dx3],
    [0, 1, dy3],
    [0, 0, 1]
])

print("\nMatriks Transformasi D → E:")
print(TDE)

print("\n=====================================\n")


# =====================================================
# 4. TRANSFORMASI E → F
# =====================================================

E = (2, 0)
F = (4, 0)

print("TRANSFORMASI E → F")
print("Titik E =", E)
print("Titik F =", F)

dx4 = F[0] - E[0]
dy4 = F[1] - E[1]

print("\nPerhitungan:")
print("Δx =", F[0], "-", E[0], "=", dx4)
print("Δy =", F[1], "-", E[1], "=", dy4)

TEF = np.array([
    [1, 0, dx4],
    [0, 1, dy4],
    [0, 0, 1]
])

print("\nMatriks Transformasi E → F:")
print(TEF)

print("\n=====================================")

TRANSFORMASI A → B
Titik A = (2, 3)
Titik B = (2, 1)

Perhitungan:
Δx = 2 - 2 = 0
Δy = 1 - 3 = -2

Matriks Transformasi A → B:
[[ 1  0  0]
 [ 0  1 -2]
 [ 0  0  1]]


TRANSFORMASI B → C
Titik B = (2, 1)
Titik C = (4, 1)

Perhitungan:
Δx = 4 - 2 = 2
Δy = 1 - 1 = 0

Matriks Transformasi B → C:
[[1 0 2]
 [0 1 0]
 [0 0 1]]


TRANSFORMASI D → E
Titik D = (2, 4)
Titik E = (2, 0)

Perhitungan:
Δx = 2 - 2 = 0
Δy = 0 - 4 = -4

Matriks Transformasi D → E:
[[ 1  0  0]
 [ 0  1 -4]
 [ 0  0  1]]


TRANSFORMASI E → F
Titik E = (2, 0)
Titik F = (4, 0)

Perhitungan:
Δx = 4 - 2 = 2
Δy = 0 - 0 = 0

Matriks Transformasi E → F:
[[1 0 2]
 [0 1 0]
 [0 0 1]]

